// August Challenge — verified local walk library.
// Maintained as data only: add/edit/remove entries here, nothing else to change.
// person: "brent" (Bellmere home base) | "leighton" (Bokarina home base)
// All distances/times marked approx in UI. verified = date info last checked.
// maps = Google Maps destination query (opens app when installed, browser otherwise).
const WALKS = [
  // ---------- BRENT — Bellmere / Caboolture / Moreton Bay ----------
  { id:"centenary-lakes", person:"brent", name:"Centenary Lakes loop", area:"Caboolture",
    start:"Centenary Lakes Park, Morayfield Rd, Caboolture", maps:"Centenary Lakes Park, Caboolture QLD",
    routeKm:2.1, routeType:"Loop", timeMin:30, difficulty:"Easy", surface:"Concrete path",
    travelKm:5, dogs:"On-leash areas + fenced off-leash zone", pram:"Yes — flat concrete, accessible toilets",
    toilets:true, parking:true, shade:"Partly shaded", water:"Water fountain near toilet block",
    desc:"Flat lakeside loop with bridges and birdlife. The easy default.",
    cautions:"Lakes unfenced; geese can be pushy in breeding season; not all shaded.",
    source:"https://www.accessible.visitmoretonbayregion.com.au/centenary-lakes-caboolture", verified:"2026-07-29", long:false },
  { id:"sheepstation-greygum", person:"brent", name:"Sheepstation Creek — Grey Gum circuit", area:"Upper Caboolture",
    start:"Williamson Rd entrance, Upper Caboolture", maps:"Sheep Station Creek Conservation Park, Williamson Road, Upper Caboolture QLD",
    routeKm:4.4, routeType:"Loop", timeMin:70, difficulty:"Easy", surface:"Bush trail",
    travelKm:7, dogs:"Not confirmed — check signage", pram:"No — natural surface",
    toilets:false, parking:true, shade:"Mostly shaded bush", water:"None — bring your own",
    desc:"231 ha of ironbark and spotted gum forest. Shared with bikes and horses.",
    cautions:"No facilities on track; take water and proper shoes.",
    source:"https://moretonbay.thyme.com.au/news-and-info/overview/sheep-station-creek-conservation-park", verified:"2026-07-29", long:false },
  { id:"sheepstation-spotted", person:"brent", name:"Sheepstation Creek — Spotted Gum trail", area:"Upper Caboolture",
    start:"Williamson Rd entrance, Upper Caboolture", maps:"Sheep Station Creek Conservation Park, Williamson Road, Upper Caboolture QLD",
    routeKm:2.4, routeType:"Return", timeMin:40, difficulty:"Easy", surface:"Bush trail (walkers only)",
    travelKm:7, dogs:"Not confirmed — check signage", pram:"No — natural surface",
    toilets:false, parking:true, shade:"Mostly shaded bush", water:"None — bring your own",
    desc:"Quieter walkers-only out-and-back through the gums.",
    cautions:"No facilities; take water.",
    source:"https://moretonbay.thyme.com.au/news-and-info/overview/sheep-station-creek-conservation-park", verified:"2026-07-29", long:false },
  { id:"wamuran-railtrail", person:"brent", name:"Caboolture–Wamuran Rail Trail", area:"Caboolture / Wamuran",
    start:"Trailhead, 51 Toohey Rd, Caboolture", maps:"Caboolture to Wamuran Rail Trail, Toohey Road, Caboolture QLD",
    routeKm:10.5, routeType:"One-way (walk any length out-and-back)", timeMin:150, difficulty:"Easy, flat",
    surface:"Sealed asphalt, 3 m wide", travelKm:6, dogs:"Allowed — dog water at trailheads", pram:"Yes — sealed and flat",
    toilets:false, parking:true, shade:"Open in sections", water:"Fountains at both trailheads",
    desc:"Flat sealed rail trail. Do the lot for a big-step day, or turn around whenever.",
    cautions:"Exposed stretches — hat and water; shared with bikes.",
    source:"https://www.railtrails.org.au/trails/caboolture-wamuran-loop-rail-trail/", verified:"2026-07-29", long:true },
  { id:"creec", person:"brent", name:"CREEC walking trails", area:"Burpengary",
    start:"Caboolture Region Environmental Education Centre, 150 Rowley Rd, Burpengary", maps:"Caboolture Region Environmental Education Centre, Rowley Road, Burpengary QLD",
    routeKm:2.2, routeType:"Loop", timeMin:45, difficulty:"Easy", surface:"Hardened track",
    travelKm:14, dogs:"Not confirmed — check signage", pram:"Partly — hardened main tracks",
    toilets:true, parking:true, shade:"Good — rainforest sections", water:"Available at centre",
    desc:"Wetlands, rainforest and Burpengary Creek in an 18 ha reserve.",
    cautions:"Check centre open hours.",
    source:"https://www.trailhiking.com.au/hikes/caboolture-walking-trails/", verified:"2026-07-29", long:false },
  { id:"palm-grove", person:"brent", name:"Palm Grove bushwalk", area:"Banksia Beach, Bribie Island",
    start:"Community Arts Centre car park, Sunderland Dr, Banksia Beach", maps:"Bribie Island Community Arts Centre, Sunderland Drive, Banksia Beach QLD",
    routeKm:1.3, routeType:"Return", timeMin:40, difficulty:"Easy", surface:"Natural rainforest track",
    travelKm:30, dogs:"No — national park", pram:"No",
    toilets:false, parking:true, shade:"Full rainforest shade", water:"None — bring your own",
    desc:"Rainforest palms and ferns to a large waterhole. Koalas about.",
    cautions:"Check QPWS park alerts before travelling.",
    source:"https://parks.qld.gov.au/parks/bribie-island/journeys/palm-grove-bicentennial-bushwalk", verified:"2026-07-29", long:false },
  { id:"banksia-melaleuca", person:"brent", name:"Banksia + Melaleuca bushwalks", area:"Banksia Beach, Bribie Island",
    start:"Community Arts Centre car park, Sunderland Dr, Banksia Beach", maps:"Bribie Island Community Arts Centre, Sunderland Drive, Banksia Beach QLD",
    routeKm:2.5, routeType:"Return", timeMin:75, difficulty:"Easy", surface:"Natural track, wetland fringes",
    travelKm:30, dogs:"No — national park", pram:"No",
    toilets:false, parking:true, shade:"Mixed", water:"None — bring your own",
    desc:"Linked Bicentennial trails through wetland and forest. Wallabies and monitors.",
    cautions:"Check QPWS park alerts; carry water.",
    source:"https://parks.qld.gov.au/parks/bribie-island/journeys/melaleuca-bicentennial-bushwalk", verified:"2026-07-29", long:false },
  { id:"buckleys-hole", person:"brent", name:"Buckleys Hole bird hide + beach", area:"Bongaree, Bribie Island",
    start:"Buckleys Hole Conservation Park, First Ave end, Bongaree", maps:"Buckleys Hole Conservation Park, Bongaree QLD",
    routeKm:2, routeType:"Return", timeMin:40, difficulty:"Easy", surface:"Sand and bush track",
    travelKm:32, dogs:"No — conservation park", pram:"No — sandy",
    toilets:false, parking:true, shade:"Partly shaded", water:"None — bring your own",
    desc:"Lagoon bird hide and quiet Pumicestone Passage beach at Bribie's southern tip.",
    cautions:"Distances approximate; soft sand sections.",
    source:"https://birdsqueensland.org.au/place/buckleys-hole-and-south-point-bribie-islands/", verified:"2026-07-29", long:false },
  { id:"north-harbour", person:"brent", name:"North Harbour Heritage Park circuit", area:"Burpengary East",
    start:"End of Moreton Bay Blvd, Burpengary East", maps:"North Harbour Heritage Park, Moreton Bay Boulevard, Burpengary East QLD",
    routeKm:2.5, routeType:"Loop", timeMin:50, difficulty:"Easy", surface:"Formed trails and boardwalk",
    travelKm:15, dogs:"On-leash in estate parkland — check signage", pram:"Mostly — formed paths",
    toilets:true, parking:true, shade:"Partly shaded", water:"Water and amenities on site",
    desc:"Riverside heritage circuit past the old homestead, dairy and wharf on the Caboolture River.",
    cautions:"Heritage Park precinct gates open 6am–6pm on weekends — check access before weekday visits.",
    source:"https://www.northharbour.com.au/north-harbour-heritage-park/activities/", verified:"2026-07-29", long:false },
  { id:"wild-horse", person:"brent", name:"Wild Horse Mountain lookout", area:"Beerburrum / Glass House",
    start:"Wild Horse Mountain car park, Johnston Rd, Coochin Creek", maps:"Wild Horse Mountain Lookout, Johnston Road, Coochin Creek QLD",
    routeKm:1.6, routeType:"Return", timeMin:45, difficulty:"Short but steep (123 m climb)", surface:"Sealed path, steep grade",
    travelKm:25, dogs:"Not confirmed — check signage", pram:"No — too steep",
    toilets:true, parking:true, shade:"Forest most of the way, rotunda on top", water:"None — bring your own",
    desc:"Short sharp climb to a fire-tower lookout with 360° views over the Glass House Mountains.",
    cautions:"Very steep even though short; vehicle break-ins reported — lock the car, take valuables.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=48512", verified:"2026-07-29", long:false },
  { id:"ngungun", person:"brent", name:"Mount Ngungun summit", area:"Glass House Mountains",
    start:"Fullertons Rd car park, Glass House Mountains", maps:"Mount Ngungun car park, Fullertons Road, Glass House Mountains QLD",
    routeKm:2.8, routeType:"Return", timeMin:75, difficulty:"Moderate — steps and rocky ridge", surface:"Forest track, steps, rock near summit",
    travelKm:24, dogs:"No — national park", pram:"No",
    toilets:false, parking:true, shade:"Tree cover almost to the top", water:"None — bring your own",
    desc:"The most doable Glass House summit — Lovers Cave halfway, full panorama of Tibrogargan and Beerwah on top.",
    cautions:"Steep cliffs at the summit; busy — go early; no toilets or water at trailhead.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=28425", verified:"2026-07-29", long:true },
  { id:"piccabeen", person:"brent", name:"Piccabeen walk — The Gantry, Mount Mee", area:"Mount Mee, D'Aguilar NP",
    start:"The Gantry day-use area, Sellin Rd, Mount Mee", maps:"The Gantry Day Use Area, Mount Mee QLD",
    routeKm:1, routeType:"Loop", timeMin:30, difficulty:"Easy (Grade 2)", surface:"Trail and boardwalk",
    travelKm:28, dogs:"No — national park", pram:"No — boardwalk sections only",
    toilets:true, parking:true, shade:"Full rainforest shade", water:"At day-use area",
    desc:"Rainforest loop through piccabeen palm groves opposite The Gantry picnic area. King parrots about.",
    cautions:"Approach from the south via Mount Mee Rd (2WD fine); check QPWS park alerts.",
    source:"https://parks.qld.gov.au/parks/daguilar/journeys/piccabeen-walk", verified:"2026-07-29", long:true },
  { id:"redcliffe-scarborough", person:"brent", name:"Redcliffe Jetty to Scarborough foreshore", area:"Redcliffe Peninsula",
    start:"Redcliffe Jetty, Redcliffe Pde, Redcliffe", maps:"Redcliffe Jetty, Redcliffe Parade, Redcliffe QLD",
    routeKm:10.4, routeType:"Return (turn around anywhere)", timeMin:130, difficulty:"Easy, flat", surface:"Paved foreshore pathway",
    travelKm:34, dogs:"Allowed on pathway (leash); check beach zones", pram:"Yes — paved",
    toilets:true, parking:true, shade:"Open in sections", water:"Fountains and parks along the way",
    desc:"Bay-side stretch of the Moreton Bay pathway past Suttons Beach, Queens Beach and Newport to Scarborough.",
    cautions:"Distance approximate — walk any length; shared with bikes; sun-exposed stretches.",
    source:"https://www.aussiebushwalking.com/qld/se-qld/redcliffe-to-scarborough-cycleway", verified:"2026-07-29", long:true },
  // ---------- LEIGHTON — Bokarina / Kawana / Sunshine Coast ----------
  { id:"bokarina-cartwright", person:"leighton", name:"Bokarina Beach to Point Cartwright", area:"Bokarina / Buddina",
    start:"Bokarina Beach car park, Bokarina Blvd", maps:"Bokarina Beach, Bokarina QLD",
    routeKm:8, routeType:"Return", timeMin:100, difficulty:"Easy, flat", surface:"Paved coastal pathway",
    travelKm:0, dogs:"On-leash on pathway; check beach zones", pram:"Yes — paved",
    toilets:true, parking:true, shade:"Exposed most of the way", water:"Fountains along pathway",
    desc:"Doorstep stretch of the Coastal Pathway north past Warana and Buddina to the lighthouse.",
    cautions:"Distance approximate — turn around anywhere; sun-exposed.",
    source:"https://www.sunshinecoast.qld.gov.au/experience-sunshine-coast/pathways-tracks-and-trails/coastal-pathway", verified:"2026-07-29", long:true },
  { id:"currimundi-cp", person:"leighton", name:"Currimundi Lake (Kathleen McArthur) circuit", area:"Wurtulla / Currimundi",
    start:"Coongarra Esplanade car park, Wurtulla", maps:"Coongarra Esplanade, Wurtulla QLD",
    routeKm:4.1, routeType:"Loop", timeMin:60, difficulty:"Easy, flat", surface:"Sandy single track + paved bits",
    travelKm:4, dogs:"No — conservation park", pram:"No — sandy track",
    toilets:true, parking:true, shade:"Shaded sections", water:"None — bring your own",
    desc:"Coastal heath, wildflowers, lake and beach views. Kathleen McArthur's wallum.",
    cautions:"Strong tidal current near lake mouth; bring water and bug spray.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=2406", verified:"2026-07-29", long:false },
  { id:"point-cartwright-loop", person:"leighton", name:"Point Cartwright loop", area:"Buddina",
    start:"La Balsa Park, Harbour Pde, Buddina (or Pacific Blvd car park)", maps:"La Balsa Park, Harbour Parade, Buddina QLD",
    routeKm:2, routeType:"Loop", timeMin:35, difficulty:"Easy", surface:"Coastal path + bushland",
    travelKm:6, dogs:"Check signage — regulated zones", pram:"Mostly — some rough edges",
    toilets:true, parking:true, shade:"Mixed", water:"Nearby at La Balsa",
    desc:"Lighthouse headland loop over the Mooloolah River mouth. Café at La Balsa.",
    cautions:"Care descending the ocean side to the beach.",
    source:"https://www.sunshinecoast.qld.gov.au/news/adventure-point-cartwright-loop-2km", verified:"2026-07-29", long:false },
  { id:"currimundi-kings", person:"leighton", name:"Coastal Pathway: Currimundi to Kings Beach", area:"Currimundi / Caloundra",
    start:"Watson St parking, Currimundi", maps:"Currimundi Lake, Currimundi QLD",
    routeKm:7, routeType:"One-way (14 km return)", timeMin:90, difficulty:"Easy", surface:"Paved pathway",
    travelKm:5, dogs:"Allowed on pathway (leash)", pram:"Yes — paved",
    toilets:true, parking:true, shade:"Exposed sections", water:"Fountains along route",
    desc:"Dicky Beach, Moffat headland and Kings Beach on one paved run south.",
    cautions:"Busy sections on weekends; one-way — plan the return.",
    source:"https://sunshinecoastwalks.com/longer-trails/currimundi-lake-to-kings-beach/", verified:"2026-07-29", long:true },
  { id:"kawana-island", person:"leighton", name:"Kawana Island waterfront loop", area:"Parrearra",
    start:"Double Bay Beach Park, Grand Pde, Parrearra", maps:"Double Bay Beach Kawana Island, Parrearra QLD",
    routeKm:5, routeType:"Loop", timeMin:65, difficulty:"Easy, flat", surface:"Paved walkway",
    travelKm:4, dogs:"On-leash", pram:"Yes — paved",
    toilets:true, parking:true, shade:"Partly shaded", water:"Park facilities",
    desc:"Waterfront circuit of the island past Double Bay's calm lagoon beach.",
    cautions:"Loop distance approximate.",
    source:"https://www.sunshinecoast.qld.gov.au/experience-sunshine-coast/beaches-and-parks/beaches-and-parks-directory/double-bay-beach-kawana-island", verified:"2026-07-29", long:false },
  { id:"ben-bennett", person:"leighton", name:"Ben Bennett Bushland Park circuit", area:"Caloundra",
    start:"Queen St entrance, Caloundra", maps:"Ben Bennett Bushland Park, Caloundra QLD",
    routeKm:1.6, routeType:"Loop", timeMin:30, difficulty:"Easy", surface:"Bush track",
    travelKm:10, dogs:"Not confirmed — check signage", pram:"No — natural surface",
    toilets:false, parking:true, shade:"Well shaded", water:"None — bring your own",
    desc:"Pocket of bushland in the middle of Caloundra. Quick green reset.",
    cautions:"None significant; mozzies after rain.",
    source:"https://www.sunshinecoast.qld.gov.au/experience-sunshine-coast/beaches-and-parks/beaches-and-parks-directory/ben-bennett-bushland-park", verified:"2026-07-29", long:false },
  { id:"mooloolaba-foreshore", person:"leighton", name:"Mooloolaba Spit to Alexandra Headland", area:"Mooloolaba",
    start:"Mooloolaba Spit car park, Parkyn Pde", maps:"Mooloolaba Spit, Parkyn Parade, Mooloolaba QLD",
    routeKm:6, routeType:"Return", timeMin:75, difficulty:"Easy, flat", surface:"Paved esplanade",
    travelKm:9, dogs:"On-leash on pathway", pram:"Yes — paved",
    toilets:true, parking:true, shade:"Some fig-tree shade", water:"Fountains along esplanade",
    desc:"Classic esplanade walk with a coffee stop at either end.",
    cautions:"Distance approximate; very busy weekend mornings; paid parking zones near the beach.",
    source:"https://www.sunshinecoast.qld.gov.au/experience-sunshine-coast/pathways-tracks-and-trails/coastal-pathway", verified:"2026-07-29", long:false },
  { id:"mount-coolum", person:"leighton", name:"Mount Coolum summit", area:"Mount Coolum",
    start:"Summit track car park, Tanah St West, Mount Coolum", maps:"Mount Coolum National Park Summit Track, Tanah Street West, Mount Coolum QLD",
    routeKm:1.6, routeType:"Return", timeMin:75, difficulty:"Hard — steep rock steps (Grade 4)", surface:"Rock steps and natural track",
    travelKm:20, dogs:"No — national park", pram:"No",
    toilets:false, parking:true, shade:"Exposed upper half", water:"None — bring your own",
    desc:"Short but serious 208 m climb. Full-coast views for the effort.",
    cautions:"Steep and slippery when wet; avoid midday heat; busy early mornings.",
    source:"https://parks.qld.gov.au/parks/mount-coolum", verified:"2026-07-29", long:true },
  { id:"lake-kawana", person:"leighton", name:"Lake Kawana rowing loop", area:"Birtinya",
    start:"Rowing finish tower, Sportsmans Pde, Birtinya (near the stadium)", maps:"Lake Kawana, Sportsmans Parade, Birtinya QLD",
    routeKm:2.4, routeType:"Loop", timeMin:35, difficulty:"Easy, flat", surface:"Wide sealed path",
    travelKm:2, dogs:"On-leash", pram:"Yes — sealed and flat",
    toilets:true, parking:true, shade:"Mostly open", water:"Facilities near stadium",
    desc:"Flat lakeside lap around the rowing end of Lake Kawana — the closest quick loop to home.",
    cautions:"Loop distance approximate; open and sunny — hat up.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=61745", verified:"2026-07-29", long:false },
  { id:"buderim-falls", person:"leighton", name:"Buderim Forest Park falls loop", area:"Buderim",
    start:"Quorn Close entrance (off Lindsay Rd), Buderim", maps:"Buderim Forest Park, Quorn Close, Buderim QLD",
    routeKm:0.8, routeType:"Loop", timeMin:45, difficulty:"Easy, one slippery rocky section", surface:"Elevated boardwalk + short trail",
    travelKm:14, dogs:"Not confirmed — check signage", pram:"Boardwalk section only",
    toilets:true, parking:true, shade:"Full rainforest shade", water:"None — bring your own",
    desc:"Rainforest boardwalk to Serenity Falls and its swimming hole. Short but a proper green reset.",
    cautions:"Rocks near the falls are slippery; mozzies after rain and late afternoon.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=18821", verified:"2026-07-29", long:false },
  { id:"mary-cairncross", person:"leighton", name:"Mary Cairncross rainforest walk", area:"Maleny",
    start:"Mary Cairncross Scenic Reserve, 148 Mountain View Rd, Maleny", maps:"Mary Cairncross Scenic Reserve, Mountain View Road, Maleny QLD",
    routeKm:1.7, routeType:"Loop", timeMin:45, difficulty:"Easy", surface:"Formed rainforest track",
    travelKm:35, dogs:"No — wildlife reserve", pram:"Yes — formed track",
    toilets:true, parking:true, shade:"Full rainforest shade", water:"At visitor centre + cafe",
    desc:"Subtropical rainforest circuit with pademelons underfoot and Glass House Mountains views from the lookout.",
    cautions:"Worth pairing with the cafe; busy on weekends; check reserve open hours.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=21220", verified:"2026-07-29", long:true },
  { id:"kondalilla", person:"leighton", name:"Kondalilla Falls circuit", area:"Montville / Flaxton",
    start:"Kondalilla Falls Rd picnic area, Flaxton", maps:"Kondalilla National Park, Kondalilla Falls Road, Flaxton QLD",
    routeKm:4.7, routeType:"Loop", timeMin:120, difficulty:"Moderate (Grade 3) — ~300 steps", surface:"Formed track with many steps",
    travelKm:35, dogs:"No — national park", pram:"No",
    toilets:true, parking:true, shade:"Mostly shaded", water:"None on track — bring your own",
    desc:"Rock pools, an 90 m waterfall and rainforest gullies. The proper hinterland workout option.",
    cautions:"Lots of steps back out; slippery when wet; check QPWS park alerts.",
    source:"https://parks.qld.gov.au/parks/kondalilla/things-to-do", verified:"2026-07-29", long:true },
  { id:"maroochy-wetlands", person:"leighton", name:"Maroochy Wetlands boardwalk", area:"Bli Bli",
    start:"Maroochy Wetlands Sanctuary, Sports Rd, Bli Bli", maps:"Maroochy Wetlands Sanctuary, Sports Road, Bli Bli QLD",
    routeKm:2, routeType:"Return", timeMin:40, difficulty:"Easy", surface:"Wide sealed boardwalk",
    travelKm:16, dogs:"Not confirmed — check signage", pram:"Yes — boardwalk, wheelchair friendly",
    toilets:true, parking:true, shade:"Mostly shaded, shade huts", water:"None — bring your own",
    desc:"Mangrove boardwalk to the Maroochy River — fiddler crabs at low tide, good birdlife.",
    cautions:"Mozzies at dawn and dusk — repellent; best at low tide.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=36831", verified:"2026-07-29", long:false },
  { id:"coolum-point-perry", person:"leighton", name:"Coolum boardwalk to Point Perry", area:"Coolum Beach",
    start:"Coolum Surf Club, David Low Way, Coolum Beach", maps:"Coolum Beach Surf Club, David Low Way, Coolum Beach QLD",
    routeKm:2.4, routeType:"Return", timeMin:40, difficulty:"Easy", surface:"Boardwalk and paved path",
    travelKm:21, dogs:"Not confirmed — check signage", pram:"Yes — stable boardwalk",
    toilets:true, parking:true, shade:"Some shelters and Norfolk pines", water:"At surf club end",
    desc:"Clifftop boardwalk from the surf club up over Point Perry — whale spotting in August.",
    cautions:"Shared with bikes; street parking fills up on good days.",
    source:"https://adventure.sunshinecoast.qld.gov.au/Home/TrailDetailsView?trailId=12418", verified:"2026-07-29", long:false }
];
